---
  swagger: "2.0"
  info: 
    version: "1.0.0"
    title: sakiewka-crypto-local
    description: Local api.
    license: 
      name: ISC
  basePath: /api
  securityDefinitions:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
  schemes: 
    - http
  consumes: 
    - application/json
  produces: 
    - application/son
  paths: 
    # ==========
    # BTC
    # ==========

    # ------------
    # USER
    # ------------

    /user/login:
      post: 
        tags: 
          - User
        description: Logs user in.
        produces: 
          - application/json
        parameters: 
          - name: body
            in: body
            required: true
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
        responses: 
          "200":
            schema: 
              type: object
              properties: 
                data:
                  type: object
                  properties:
                    name: 
                      type: string
                    password: 
                      type: string
          default: 
            description: unexpected error
            schema: 
              $ref: "#/definitions/ErrorModel"

    /user/register:
      post: 
        tags: 
          - User
        description: Registers user.
        produces: 
          - application/json
        parameters: 
          - name: body
            in: body
            required: true
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
        responses: 
          "200":
            schema: 
              type: object
              properties: 
                data:
                  type: object
                  properties:
                    status: 
                      type: string
          default: 
            description: unexpected error
            schema: 
              $ref: "#/definitions/ErrorModel"

    /user/info:
      get: 
        tags: 
          - User
        description: Shows user info.
        produces: 
          - application/json
        security:
          - Bearer: []
        responses: 
          "200":
            schema: 
              type: object
              properties: 
                data:
                  type: object
                  properties:
                    email: 
                      type: string
                    token: 
                      type: string
                    tokenInfo: 
                      type: string
          default: 
            description: unexpected error
            schema: 
              $ref: "#/definitions/ErrorModel"

    # ------------
    # WALLET
    # ------------

    /btc/wallet:
      post: 
        tags: 
          - BTC - wallet
        description: Creates new wallet.
        produces: 
          - application/json
        security:
          - Bearer: []
        parameters:
          - name: body
            in: body
            required: true
            schema:
              type: object
              properties:
                name:
                  type: string
                passphrase:
                  type: string
                userPubKey:
                  type: string
                backupPubKey:
                  type: string
        responses:
          "200":
            description: success
            schema: 
              type: object
              properties: 
                data:
                  type: object
                  properties:
                    id: 
                      type: string
                    initialAddress: 
                      type: string
                    servicePubKey: 
                      type: string
                    keys: 
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                          type:
                            type: string
          default: 
            description: unexpected error
            schema: 
              $ref: "#/definitions/ErrorModel"
      get: 
        tags: 
          - BTC - wallet
        description: Lists user wallets.
        produces: 
          - application/json
        security:
          - Bearer: []
        parameters:
          - name: nextPageToken
            in: query
            required: false
            type: string
          - name: limit
            in: query
            required: true
            type: integer
        responses: 
          "200":
            schema: 
              type: object
              properties: 
                data:
                  type: object
                  properties:
                    nextPageToken: 
                      type: string
                    wallets: 
                      type: array
                      items:
                        type: object
          default: 
            description: unexpected error
            schema: 
              $ref: "#/definitions/ErrorModel"

    /btc/wallet/{walletId}:
      get: 
        tags: 
          - BTC - wallet
        description: Shows user wallet details.
        produces: 
          - application/json
        security:
          - Bearer: []
        parameters: 
          - name: walletId
            in: path
            required: true
            description: wallet id
            type: string
        responses: 
          "200":
            schema: 
              type: object
              properties: 
                data:
                  type: object
                  properties:
                    id: 
                      type: string
                    name: 
                      type: string
                    currency: 
                      type: string
                    created: 
                      type: string
                    keys: 
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                          type:
                            type: string
          default: 
            description: unexpected error
            schema: 
              $ref: "#/definitions/ErrorModel"

    /btc/wallet/{walletId}/balance:
      get: 
        tags: 
          - BTC - wallet
        description: Shows wallet balance.
        produces: 
          - application/json
        security:
          - Bearer: []
        parameters:
          - name: walletId
            in: path
            required: true
            description: wallet id
            type: string
        responses: 
          "200":
            schema: 
              type: object
              properties: 
                data:
                  type: object
                  properties:
                    confirming: 
                      type: integer
                    confirmed: 
                      type: integer
                    locked: 
                      type: integer
          default: 
            description: unexpected error
            schema: 
              $ref: "#/definitions/ErrorModel"

    /btc/wallet/{walletId}/address:
      post: 
        tags: 
          - BTC - wallet
        description: Creates new wallet address.
        produces: 
          - application/json
        security:
          - Bearer: []
        parameters: 
          - name: walletId
            in: path
            required: true
            description: wallet id
            type: string
          - name: body
            in: body
            schema:
              type: object
              properties:
                name: 
                  type: string
        responses: 
          "200":
            schema: 
              type: object
              properties: 
                data:
                  type: object
                  properties:
                    address: 
                      type: string
                    path: 
                      type: object
                      items:
                        properties:
                          cosignerIndex:
                            type: string
                          change:
                            type: string
                          addressIndex:
                            type: string
          default: 
            description: unexpected error
            schema: 
              $ref: "#/definitions/ErrorModel"

      get: 
        tags: 
          - BTC - wallet
        description: List addresses.
        produces: 
          - application/json
        security:
          - Bearer: []
        parameters: 
          - name: nextPageToken
            in: query
            required: false
            type: string
          - name: limit
            in: query
            required: true
            type: integer
          - name: walletId
            in: path
            required: true
            description: wallet id
            type: string
        responses: 
          "200":
            schema: 
              type: object
              properties: 
                data:
                  type: object
                  properties:
                    addresses: 
                      type: array
                      items:
                        type: object
                        properties:
                          address: 
                            type: string
                          name: 
                            type: string
                          created: 
                            type: string
                          path: 
                            type: object
                            properties:
                              cosignerIndex:
                                type: string
                              change:
                                type: string
                              addressIndex:
                                type: string
          default: 
            description: unexpected error
            schema: 
              $ref: "#/definitions/ErrorModel"

    /btc/wallet/{walletId}/address/{addressId}:
      get: 
        tags: 
          - BTC - wallet
        description: Shows address details.
        produces: 
          - application/json
        security:
          - Bearer: []
        parameters: 
          - name: walletId
            in: path
            required: true
            description: wallet id
            type: string
          - name: addressId
            in: path
            required: true
            description: address id
            type: string
        responses: 
          "200":
            schema: 
              type: object
              properties: 
                data:
                  type: object
                  properties:
                    address: 
                      type: string
                    name: 
                      type: string
                    created: 
                      type: string
                    path: 
                      type: object
                      properties:
                        cosignerIndex:
                          type: string
                        change:
                          type: string
                        addressIndex:
                          type: string
          default: 
            description: unexpected error
            schema: 
              $ref: "#/definitions/ErrorModel"

    # ------------
    # KEY
    # ------------

    /btc/key:
      post: 
        tags: 
          - BTC - key
        description: Creates new key.
        produces: 
          - application/json
        parameters: 
          - name: body
            in: body
            required: true
            schema:
              type: object
              properties:
                passphrase:
                  type: string
        responses: 
          "200":
            schema: 
              type: object
              properties: 
                data:
                  type: object
                  properties:
                    keyPair:
                      type: object
                      properties:
                        pubKey:
                          type: string
                        prvKey:
                          type: string
          default: 
            description: unexpected error
            schema: 
              $ref: "#/definitions/ErrorModel"

    /btc/key/{keyId}:
      get: 
        tags: 
          - BTC - key
        description: Shows key details.
        produces: 
          - application/json
        security:
          - Bearer: []
        parameters: 
          - name: includePrivate
            in: query
            required: false
            type: string
          - name: keyId
            in: path
            required: true
            description: key id
            type: string
        responses: 
          "200":
            schema: 
              type: object
              properties: 
                data:
                  type: object
                  properties:
                    id: 
                      type: string
                    pubKey: 
                      type: string
                    prvKey: 
                      type: string
                    keyType: 
                      type: string
                    created: 
                      type: string
          default: 
            description: unexpected error
            schema: 
              $ref: "#/definitions/ErrorModel"

  # ==========
  # MODELS
  # ==========

  definitions: 

    ResponseModel: 
      type: object
      properties: 
        data:
          type: object

    ErrorModel: 
      type: object
      properties: 
        error:
          type: object
          properties:
            message: 
              type: string
