---
  swagger: "2.0"
  info: 
    version: "1.0.0"
    title: sakiewka-crypto-local
    description: Local api.
    license: 
      name: ISC
  basePath: /api
  schemes: 
    - http
  consumes: 
    - application/json
  produces: 
    - application/json
  paths: 
    /user/login:
      post: 
        tags: 
          - User
        description: Logs user in.
        produces: 
          - application/json
        parameters: 
          - 
            name: email
            in: body
            required: true
            type: string
          - 
            name: password
            in: body
            required: true
            type: string
        responses: 
          "200":
            schema: 
              type: object
              properties: 
                data:
                  type: object
                  properties:
                    name: 
                      type: string
                    password: 
                      type: string
          default: 
            description: unexpected error
            schema: 
              $ref: "#/definitions/ErrorModel"
    /user/register:
      post: 
        tags: 
          - User
        description: Registers user.
        produces: 
          - application/json
        parameters: 
          - 
            name: email
            in: body
            required: true
            type: string
          - 
            name: password
            in: body
            required: true
            type: string
        responses: 
          "200":
            schema: 
              type: object
              properties: 
                data:
                  type: object
                  properties:
                    status: 
                      type: string
          default: 
            description: unexpected error
            schema: 
              $ref: "#/definitions/ErrorModel"
    /user/info:
      get: 
        tags: 
          - User
        description: Shows user info.
        produces: 
          - application/json
        parameters: 
          - 
            name: Authentication
            in: header
            required: true
            type: string
        responses: 
          "200":
            schema: 
              type: object
              properties: 
                data:
                  type: object
                  properties:
                    email: 
                      type: string
                    token: 
                      type: string
                    tokenInfo: 
                      type: string
          default: 
            description: unexpected error
            schema: 
              $ref: "#/definitions/ErrorModel"
    /btc/wallet:
      post: 
        tags: 
          - BTC - wallet
        description: Creates new wallet.
        produces: 
          - application/json
        parameters:
          - 
            name: Authentication
            in: header
            required: true
            type: string
          - 
            name: name
            in: body
            required: true
            type: string
          - 
            name: passphrase
            in: body
            required: true
            type: string
          - 
            name: userPubKey
            in: body
            required: false
            type: string
          - 
            name: backupPubKey
            in: body
            required: false
            type: string
        responses:
          "200":
            description: success
            schema: 
              type: object
              properties: 
                data:
                  type: object
                  properties:
                    id: 
                      type: string
                    initialAddress: 
                      type: string
                    servicePubKey: 
                      type: string
                    keys: 
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                          type:
                            type: string
          default: 
            description: unexpected error
            schema: 
              $ref: "#/definitions/ErrorModel"
    /btc/wallet:
      get: 
        tags: 
          - BTC - wallet
        description: Lists user wallets.
        produces: 
          - application/json
        parameters:
          - 
            name: Authentication
            in: header
            required: true
            type: string
          - 
            name: nextPageToken
            in: query
            required: false
            type: string
          - 
            name: limit
            in: query
            required: true
            type: string
        responses: 
          "200":
            schema: 
              type: object
              properties: 
                data:
                  type: object
                  properties:
                    nextPageToken: 
                      type: string
                    wallets: 
                      type: array
                      items:
                        type: object
          default: 
            description: unexpected error
            schema: 
              $ref: "#/definitions/ErrorModel"
    /btc/wallet/{walletId}:
      get: 
        tags: 
          - BTC - wallet
        description: Shows user wallet details.
        produces: 
          - application/json
        parameters: 
          - 
            name: Authentication
            in: header
            required: true
            type: string
          - 
        responses: 
          "200":
            schema: 
              type: object
              properties: 
                data:
                  type: object
                  properties:
                    id: 
                      type: string
                    name: 
                      type: string
                    currency: 
                      type: string
                    created: 
                      type: string
                    keys: 
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                          type:
                            type: string
          default: 
            description: unexpected error
            schema: 
              $ref: "#/definitions/ErrorModel"
    /btc/wallet/{walletId}/address:
      post: 
        tags: 
          - BTC - wallet
        description: Creates new wallet address.
        produces: 
          - application/json
        parameters: 
          - 
            name: Authentication
            in: header
            required: true
            type: string
          - 
            name: name
            in: body
            required: true
            type: string
        responses: 
          "200":
            schema: 
              type: object
              properties: 
                data:
                  type: object
                  properties:
                    address: 
                      type: string
                    path: 
                      type: object
                      items:
                        properties:
                          cosignerIndex:
                            type: string
                          change:
                            type: string
                          addressIndex:
                            type: string
          default: 
            description: unexpected error
            schema: 
              $ref: "#/definitions/ErrorModel"
      get: 
        tags: 
          - BTC - wallet
        description: List addresses.
        produces: 
          - application/json
        parameters: 
          - 
            name: Authentication
            in: header
            required: true
            type: string
          - 
            name: nextPageToken
            in: query
            required: false
            type: string
          - 
            name: limit
            in: query
            required: true
            type: string
        responses: 
          "200":
            schema: 
              type: object
              properties: 
                data:
                  type: object
                  properties:
                    addresses: 
                      type: array
                      items:
                        type: object
                        properties:
                          address: 
                            type: string
                          name: 
                            type: string
                          created: 
                            type: string
                          path: 
                            type: object
                            properties:
                              cosignerIndex:
                                type: string
                              change:
                                type: string
                              addressIndex:
                                type: string
          default: 
            description: unexpected error
            schema: 
              $ref: "#/definitions/ErrorModel"
    /btc/wallet/{walletId}/address/{addressId}:
      get: 
        tags: 
          - BTC - wallet
        description: Shows address details.
        produces: 
          - application/json
        parameters: 
          - 
            name: Authentication
            in: header
            required: true
            type: string
        responses: 
          "200":
            schema: 
              type: object
              properties: 
                data:
                  type: object
                  properties:
                    address: 
                      type: string
                    name: 
                      type: string
                    created: 
                      type: string
                    path: 
                      type: object
                      properties:
                        cosignerIndex:
                          type: string
                        change:
                          type: string
                        addressIndex:
                          type: string
          default: 
            description: unexpected error
            schema: 
              $ref: "#/definitions/ErrorModel"
    /btc/key:
      post: 
        tags: 
          - BTC - key
        description: Creates new key.
        produces: 
          - application/json
        parameters: 
          - 
            name: passphrase
            in: body
            required: true
            type: string
        responses: 
          "200":
            schema: 
              type: object
              properties: 
                data:
                  type: object
                  properties:
                    keyPair:
                      type: object
                      properties:
                        pubKey:
                          type: string
                        prvKey:
                          type: string
          default: 
            description: unexpected error
            schema: 
              $ref: "#/definitions/ErrorModel"
    /btc/key/{keyId}:
      get: 
        tags: 
          - BTC - key
        description: Shows key details.
        produces: 
          - application/json
        parameters: 
          - 
            name: Authentication
            in: header
            required: true
            type: string
          - 
            name: includePrivate
            in: query
            required: false
            type: string
        responses: 
          "200":
            schema: 
              type: object
              properties: 
                data:
                  type: object
                  properties:
                    id: 
                      type: string
                    pubKey: 
                      type: string
                    prvKey: 
                      type: string
                    keyType: 
                      type: string
                    created: 
                      type: string
          default: 
            description: unexpected error
            schema: 
              $ref: "#/definitions/ErrorModel"
    /eth/wallet/send-coins:
      post: 
        tags: 
          - ETH - wallet
        description: Sends eth.
        produces: 
          - application/json
        parameters:
          - 
            name: Authentication
            in: header
            required: true
            type: string
          - 
            name: address
            in: body
            required: true
            type: string
          - 
            name: amount
            in: body
            required: true
            type: string
          - 
            name: data
            in: body
            required: false
            type: string
          - 
            name: prvKey
            in: body
            required: false
            type: string
        responses: 
          "200":
            schema: 
              type: object
              properties: 
                data:
                  type: object
                  properties:
                    success: 
                      type: string
          default: 
            description: unexpected error
            schema: 
              $ref: "#/definitions/ErrorModel"
    /eth/wallet/send-tokens:
      post: 
        tags: 
          - ETH - wallet
        description: Sends tokens.
        produces: 
          - application/json
        parameters:
          - 
            name: Authentication
            in: header
            required: true
            type: string
          - 
            name: address
            in: body
            required: true
            type: string
          - 
            name: contractAddress
            in: body
            required: true
            type: string
          - 
            name: amount
            in: body
            required: true
            type: string
          - 
            name: prvKey
            in: body
            required: false
            type: string
        responses: 
          "200":
            schema: 
              type: object
              properties: 
                data:
                  type: object
                  properties:
                    success: 
                      type: string
          default: 
            description: unexpected error
            schema: 
              $ref: "#/definitions/ErrorModel"
  definitions: 
    ResponseModel: 
      type: object
      properties: 
        data:
          type: object
    ErrorModel: 
      type: object
      properties: 
        error:
          type: object
          properties:
            message: 
              type: string
